version: '3.9'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: citisafe-db
    restart: always
    environment:
      POSTGRES_DB: citisafe
      POSTGRES_USER: citisafe_user
      POSTGRES_PASSWORD: citisafe123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: